name: Deploy life

on:
  push:
    branches:
      - master
    paths:
      - "life/**"
      - ".github/workflows/deploy-life.yml"
      - "**/package.json"
      - "**/pnpm-lock.yaml"
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - "life/**"
      - ".github/workflows/deploy-life.yml"
      - "**/package.json"
      - "**/pnpm-lock.yaml"

jobs:
  deploy-life:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]
        deploy-dir: [life/.vitepress/dist]
        deploy-user: [augusmeow]
        deploy-repo: [life, augusmeow.github.io]

    runs-on: ${{ matrix.os }}

    # # only me, deploy
    # if: github.actor == 'DrAugus'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Change config
        run: mv ./life/.vitepress/config.ts.replace ./life/.vitepress/config.ts
        if: ${{ matrix.deploy-repo == 'life' }}

      # 运行构建脚本
      - name: Build VitePress site
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm life:build

      - name: Add google
        run: |
          echo "google-site-verification: googlea936c3462e7f8864.html" >> ./life/.vitepress/dist/googlea936c3462e7f8864.html
        if: ${{ matrix.deploy-repo == 'augusmeow.github.io' }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          repo: ${{ matrix.deploy-user }}/${{ matrix.deploy-repo }}
          target_branch: gh-pages
          build_dir: ${{ matrix.deploy-dir }}
          jekyll: false
        env:
          GH_PAT: ${{ secrets.DEPLOY_GH }}
